export const ActionTypes = {
  SERVER_NOT_REPLY: 'SERVER_NOT_REPLY',
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  MOST_SEARCH_REQUEST: 'MOST_SEARCH_REQUEST',
  MOST_SEARCH_SUCCESSED: 'MOST_SEARCH_SUCCESSED',
  MOST_SEARCH_FAILED: 'MOST_SEARCH_FAILED',
  ROOM_NEW_REQUEST: 'ROOM_NEW_REQUEST',
  ROOM_NEW_SUCCESSED: 'ROOM_NEW_SUCCESSED',
  ROOM_NEW_FAILED: 'ROOM_NEW_FAILED',
}